Repository jupyter-robotics/jupyterlab-niryo-one, pull requests merged in 2022-07, with the labels that each got.

#1 added top level initialization
  src/niryo_one_python_generators.js
  yarn.lock
Labels: enhancement

#2 Rename repository
  README.md
  RELEASE.md
Labels: maintenance

#3 Extend jupyterlab-blockly
  .gitignore
  package.json
  patches/@jupyterlab+codeeditor+3.4.3.patch
  setup.py
  src/index.ts
  src/niryo_one_python_generators.js
  yarn-error.log
  yarn.lock
Labels: enhancement

#5 Automated Changelog Entry for 0.1.0a0 on main
  .eslintignore
  .prettierignore
  CHANGELOG.md
Labels: documentation
