Repository jupyter-robotics/jupyterlab-niryo-one, pull requests merged in 2022-08, with the labels that each got.

#7 Update existing blocks to newest API and add new blocks
  package.json
  src/niryo_one_python_generators.js
  yarn.lock
Labels: bug, enhancement

#8 Add missing arguments
  src/niryo_one_python_generators.js
Labels: bug

#10 Updated to latest version of `jupyterlab-blockly`
  package-lock.json
  package.json
  setup.py
  src/index.ts
  yarn.lock
Labels: maintenance

#11 Added a toolbox for the Ned2 robot
  README.md
  src/index.ts
  src/niryo_one_python_generators.js
Labels: enhancement
